version: '3.8'    

services:
  postgres:
    image: postgres:latest
    # image: db
    # container_name: db
    build:
      context: .
      # context: ./db
      # target: db
      # dockerfile: db/Dockerfile
    environment:
      POSTGRES_DB: jobly
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./db/scripts/:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
      # - "8081:3001"
    depends_on:
      - postgres
      # - db
    environment:
      PGHOST: postgres
      PGUSER: myuser
      PGPASSWORD: mypassword
      PGDATABASE: jobly
      PGPORT: 5432
      # PGSSLMODE: disable

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
      # - "8080:3000"
    depends_on:
      - backend
